//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPWebForm_emdep.vn.cms.admin.TinTuc.DanhMucTin
{


    public partial class DanhMucTin_HienThi
    {
    }
}
